---
- name: Deploy centralized server
  hosts: all
  vars:
    user: <REPLACE_WITH_YOUR_USER>
    centralized_server_binary_path: "../../target/release-lto/hotshot-centralized-server-bin"
    config_toml_path: "./config.toml"
    server_host: "0.0.0.0"
    server_port: "2345"
  remote_user: "{{user}}"

  tasks:
  - name: Copy binary onto centralized server host
    copy:
      src: "{{centralized_server_binary_path}}"
      dest: "~/"
      mode: '0755'

  - name: Copy config.toml onto each host
    copy:
      src: "{{config_toml_path}}"
      dest: "~/"

  - name: Run server
    command: './hotshot-centralized-server-bin {{server_host}} {{server_port}}'