version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/phaselock-testing"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/phaselock-types"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/phaselock-utils"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/libp2p-networking"
    schedule:
      interval: "daily"
