version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  groups:
    all:
      patterns:
        - "*"
      exclude-patterns:
        - "cdn-*"
    cdn:
      patterns:
        - "cdn-*"
