var sourcesIndex = {};
sourcesIndex["clichat"] = {"name":"","files":["clichat.rs"]};
sourcesIndex["counter"] = {"name":"","dirs":[{"name":"common","files":["lossy_network.rs","mod.rs","web.rs"]}],"files":["counter.rs"]};
sourcesIndex["dentry_simulator"] = {"name":"","files":["dentry-simulator.rs"]};
sourcesIndex["hotshot"] = {"name":"","dirs":[{"name":"demos","files":["dentry.rs"]},{"name":"tasks","files":["mod.rs"]},{"name":"traits","dirs":[{"name":"networking","files":["centralized_server_network.rs","libp2p_network.rs","memory_network.rs","w_network.rs"]},{"name":"storage","files":["memory_storage.rs"]}],"files":["election.rs","networking.rs","node_implementation.rs","storage.rs"]},{"name":"types","files":["event.rs","handle.rs"]}],"files":["committee.rs","data.rs","demos.rs","documentation.rs","lib.rs","traits.rs","types.rs","utils.rs"]};
sourcesIndex["hotshot_centralized_server_bin"] = {"name":"","files":["main.rs"]};
sourcesIndex["libp2p_networking"] = {"name":"","dirs":[{"name":"network","dirs":[{"name":"behaviours","files":["dht.rs","direct_message.rs","direct_message_codec.rs","exponential_backoff.rs","gossip.rs","mod.rs"]},{"name":"node","files":["config.rs","handle.rs"]}],"files":["def.rs","error.rs","mod.rs","node.rs"]}],"files":["lib.rs","message.rs"]};
sourcesIndex["multi_machine"] = {"name":"","files":["multi-machine.rs"]};
sourcesIndex["multi_machine_centralized"] = {"name":"","files":["multi-machine-centralized.rs"]};
sourcesIndex["multi_machine_libp2p"] = {"name":"","files":["multi-machine-libp2p.rs"]};
createSourceSidebar();
