[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-serialize = { workspace = true }
jf-primitives = { workspace = true }
quinn = { workspace = true }
rcgen = "0.12.0"
common = { path = "../common" }
chrono = { workspace = true }
rustls = { workspace = true }
pem = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
redis = { version = "0.24.0", features = ["tokio-comp", "ahash"] }
tracing = { workspace = true }
client = { path = "../client" }
sha2 = "0.10.8"
hex = "0.4.3"