//! Vote and vote accumulator types
//!
//! This module contains types used to represent the various types of votes that `HotShot` nodes
//! can send, and vote accumulator that converts votes into certificates.

use crate::{
    certificate::{QuorumCertificate, AssembledSignature},
    data::LeafType,
    traits::{
        election::{VoteData, VoteToken},
        node_implementation::NodeType,
        signature_key::{EncodedPublicKey, EncodedSignature, SignatureKey,},
    },
};
use commit::{Commitment, Committable};
use either::Either;
use ethereum_types::U256;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};
use std::fmt::Debug;
use std::num::NonZeroU64;
use tracing::error;
use bincode::Options;
use hotshot_utils::bincode::bincode_opts;
use bitvec::prelude::*;
use jf_primitives::signatures::{bls_over_bn254::{BLSOverBN254CurveSignatureScheme}};
use jf_primitives::signatures::SignatureScheme;

/// The vote sent by consensus messages.
pub trait VoteType<TYPES: NodeType>:
    Debug + Clone + 'static + Serialize + for<'a> Deserialize<'a> + Send + Sync + PartialEq
{
    /// The view this vote was cast for.
    fn current_view(&self) -> TYPES::Time;
}

/// A vote on DA proposal.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Hash, Eq)]
#[serde(bound(deserialize = ""))]
pub struct DAVote<TYPES: NodeType> {
    /// The signature share associated with this vote
    /// TODO ct/vrf make ConsensusMessage generic over I instead of serializing to a [`Vec<u8>`]
    // signature.2 = entry including public key for certificate aggregation
    pub signature: (EncodedPublicKey, EncodedSignature),
    /// The block commitment being voted on.
    pub block_commitment: Commitment<TYPES::BlockType>,
    /// The view this vote was cast for
    pub current_view: TYPES::Time,
    /// The vote token generated by this replica
    pub vote_token: TYPES::VoteTokenType,
    /// The vote data this vote is signed over
    pub vote_data: VoteData<TYPES::BlockType>,
}

/// A positive or negative vote on validating or commitment proposal.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
#[serde(bound(deserialize = ""))]
pub struct YesOrNoVote<TYPES: NodeType, LEAF: LeafType<NodeType = TYPES>> {
    /// TODO we should remove this
    /// this is correct, but highly inefficient
    /// we should check a cache, and if that fails request the qc
    pub justify_qc_commitment: Commitment<QuorumCertificate<TYPES, LEAF>>,
    /// The signature share associated with this vote
    /// TODO ct/vrf make ConsensusMessage generic over I instead of serializing to a [`Vec<u8>`]
    // signature.2 = entry with public key for certificate aggregation
    pub signature: (EncodedPublicKey, EncodedSignature),
    /// The leaf commitment being voted on.
    pub leaf_commitment: Commitment<LEAF>,
    /// The view this vote was cast for
    pub current_view: TYPES::Time,
    /// The vote token generated by this replica
    pub vote_token: TYPES::VoteTokenType,
    /// The vote data this vote is signed over
    pub vote_data: VoteData<LEAF>,
}

/// A timeout vote.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
#[serde(bound(deserialize = ""))]
pub struct TimeoutVote<TYPES: NodeType, LEAF: LeafType<NodeType = TYPES>> {
    /// The justification qc for this view
    // TODO ED This should be the high_qc instead, and the signature should be over it,
    // not just over the view number
    pub justify_qc: QuorumCertificate<TYPES, LEAF>,
    /// The signature share associated with this vote
    /// TODO ct/vrf make ConsensusMessage generic over I instead of serializing to a [`Vec<u8>`]
    // signature.2 = entry with public key for certificate aggregation
    pub signature: (EncodedPublicKey, EncodedSignature),
    /// The view this vote was cast for
    pub current_view: TYPES::Time,
    /// The vote token generated by this replica
    pub vote_token: TYPES::VoteTokenType,
    /// The vote data this vote is signed over
    pub vote_data: VoteData<TYPES::Time>,
}

/// The internals of a view sync vote
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
#[serde(bound(deserialize = ""))]
pub struct ViewSyncVoteInternal<TYPES: NodeType> {
    /// The relay this vote is intended for
    pub relay_pub_key: EncodedPublicKey,

    pub relay: u64,
    /// The view number we are trying to sync on
    pub round: TYPES::Time,
    /// This node's signature over the VoteData
    pub signature: (EncodedPublicKey, EncodedSignature),
    /// The vote token generated by this replica
    pub vote_token: TYPES::VoteTokenType,
    /// The vote data this vote is signed over
    pub vote_data: VoteData<ViewSyncData<TYPES>>,
}

/// The data View Sync votes are signed over
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Hash, Eq)]
#[serde(bound(deserialize = ""))]
pub struct ViewSyncData<TYPES: NodeType> {
    /// The relay this vote is intended for
    pub relay: EncodedPublicKey,
    /// The view number we are trying to sync on
    pub round: TYPES::Time,
}

impl<TYPES: NodeType> Committable for ViewSyncData<TYPES> {
    fn commit(&self) -> Commitment<Self> {
        let builder = commit::RawCommitmentBuilder::new("Quorum Certificate Commitment");

        builder
            .var_size_field("Relay public key", &self.relay.0)
            .u64(*self.round)
            .finalize()
    }
}

/// Votes to synchronize the network on a single view
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
#[serde(bound(deserialize = ""))]
pub enum ViewSyncVote<TYPES: NodeType> {
    /// PreCommit vote
    PreCommit(ViewSyncVoteInternal<TYPES>),
    /// Commit vote
    Commit(ViewSyncVoteInternal<TYPES>),
    /// Finalize vote
    Finalize(ViewSyncVoteInternal<TYPES>),
}

impl<TYPES: NodeType> ViewSyncVote<TYPES> {
    pub fn signature(&self) -> EncodedSignature {
        match &self {
            ViewSyncVote::PreCommit(vote_internal)
            | ViewSyncVote::Commit(vote_internal)
            | ViewSyncVote::Finalize(vote_internal) => vote_internal.signature.1.clone(),
        }
    }
    pub fn signature_key(&self) -> TYPES::SignatureKey {
        let encoded = match &self {
            ViewSyncVote::PreCommit(vote_internal)
            | ViewSyncVote::Commit(vote_internal)
            | ViewSyncVote::Finalize(vote_internal) => vote_internal.signature.0.clone(),
        };
        <TYPES::SignatureKey as SignatureKey>::from_bytes(&encoded).unwrap()
    }

    pub fn relay(&self) -> u64 {
        match &self {
            ViewSyncVote::PreCommit(vote_internal)
            | ViewSyncVote::Commit(vote_internal)
            | ViewSyncVote::Finalize(vote_internal) => vote_internal.relay,
        }
    }

    pub fn round(&self) -> TYPES::Time {
        match &self {
            ViewSyncVote::PreCommit(vote_internal)
            | ViewSyncVote::Commit(vote_internal)
            | ViewSyncVote::Finalize(vote_internal) => vote_internal.round,
        }
    }
}

/// Votes on validating or commitment proposal.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Hash)]
#[serde(bound(deserialize = ""))]
pub enum QuorumVote<TYPES: NodeType, LEAF: LeafType<NodeType = TYPES>> {
    /// Posivite vote.
    Yes(YesOrNoVote<TYPES, LEAF>),
    /// Negative vote.
    No(YesOrNoVote<TYPES, LEAF>),
    /// Timeout vote.
    Timeout(TimeoutVote<TYPES, LEAF>),
}

impl<TYPES: NodeType> VoteType<TYPES> for DAVote<TYPES> {
    fn current_view(&self) -> TYPES::Time {
        self.current_view
    }
}

impl<TYPES: NodeType> DAVote<TYPES> {
    pub fn signature_key(&self) -> TYPES::SignatureKey {
        <TYPES::SignatureKey as SignatureKey>::from_bytes(&self.signature.0).unwrap()
    }
}

impl<TYPES: NodeType, LEAF: LeafType<NodeType = TYPES>> VoteType<TYPES>
    for QuorumVote<TYPES, LEAF>
{
    fn current_view(&self) -> TYPES::Time {
        match self {
            QuorumVote::Yes(v) | QuorumVote::No(v) => v.current_view,
            QuorumVote::Timeout(v) => v.current_view,
        }
    }
}

impl<TYPES: NodeType, LEAF: LeafType<NodeType = TYPES>> QuorumVote<TYPES, LEAF> {
    pub fn signature(&self) -> EncodedSignature {
        match &self {
            Self::Yes(vote) | Self::No(vote) => vote.signature.1.clone(),
            Self::Timeout(vote) => vote.signature.1.clone(),
        }
    }
    pub fn signature_key(&self) -> TYPES::SignatureKey {
        let encoded = match &self {
            Self::Yes(vote) | Self::No(vote) => vote.signature.0.clone(),
            Self::Timeout(vote) => vote.signature.0.clone(),
        };
        <TYPES::SignatureKey as SignatureKey>::from_bytes(&encoded).unwrap()
    }
}

impl<TYPES: NodeType> VoteType<TYPES> for ViewSyncVote<TYPES> {
    fn current_view(&self) -> TYPES::Time {
        match self {
            ViewSyncVote::PreCommit(v) | ViewSyncVote::Commit(v) | ViewSyncVote::Finalize(v) => {
                v.round
            }
        }
    }
}

/// The aggreation of votes, implemented by `VoteAccumulator`.
pub trait Accumulator<T, U>: Sized {
    /// Accumate the `val` to the current state.
    ///
    /// If a threshold is reached, returns `U` (e.g., a certificate). Else, returns `Self` and
    /// continues accumulating items.
    fn append(self, val: T) -> Either<Self, U>;
}

/// Mapping of commitments to vote tokens by key.
type VoteMap<C, TOKEN> = HashMap<
    Commitment<C>,
    (
        u64,
        BTreeMap<EncodedPublicKey, (EncodedSignature, VoteData<C>, TOKEN)>,
    ),
>;

/// Describe the process of collecting signatures on block or leaf commitment, to form a DAC or QC,
/// respectively.
pub struct VoteAccumulator<TOKEN, COMMITMENT: Committable + Serialize + Clone> {
    /// Map of all signatures accumlated so far
    pub total_vote_outcomes: VoteMap<COMMITMENT, TOKEN>,
    /// Map of all da signatures accumlated so far
    pub da_vote_outcomes: VoteMap<COMMITMENT, TOKEN>,
    /// Map of all yes signatures accumlated so far
    pub yes_vote_outcomes: VoteMap<COMMITMENT, TOKEN>,
    /// Map of all no signatures accumlated so far
    pub no_vote_outcomes: VoteMap<COMMITMENT, TOKEN>,
    /// Map of all view sync precommit votes accumulated thus far
    pub viewsync_precommit_vote_outcomes: VoteMap<COMMITMENT, TOKEN>,
    /// Map of all view sync commit votes accumulated thus far
    pub viewsync_commit_vote_outcomes: VoteMap<COMMITMENT, TOKEN>,
    /// Map of all view sync finalize votes accumulated thus far
    pub viewsync_finalize_vote_outcomes: VoteMap<COMMITMENT, TOKEN>,
    /// A quorum's worth of stake, generall 2f + 1
    pub success_threshold: NonZeroU64,
    /// Enough stake to know that we cannot possibly get a quorum, generally f + 1
    pub failure_threshold: NonZeroU64,
    /// A list of valid signatures for certificate aggregation
    pub sig_lists: Vec<<BLSOverBN254CurveSignatureScheme as SignatureScheme>::Signature>,
    /// A bitvec to indicate which node is active and send out a valid signature for certificate aggregation, this automatically do uniqueness check
    pub signers: BitVec,
}

impl<TOKEN, LEAF: Committable + Serialize + Clone, TYPES: NodeType>
    Accumulator<
        (
            Commitment<LEAF>,
            (EncodedPublicKey, (EncodedSignature, Vec<<TYPES::SignatureKey as SignatureKey>::StakeTableEntry>,  usize, VoteData<LEAF>, TOKEN)),
        ),
        AssembledSignature<TYPES>,
    > for VoteAccumulator<TOKEN, LEAF>
where
    TOKEN: Clone + VoteToken,
{
    fn append(
        mut self,
        val: (
            Commitment<LEAF>,
            (EncodedPublicKey, (EncodedSignature, Vec<<TYPES::SignatureKey as SignatureKey>::StakeTableEntry>, usize, VoteData<LEAF>, TOKEN)),
        ),
    ) -> Either<Self, AssembledSignature<TYPES>> {
        let (commitment, (key, (sig, entries, node_id, vote_data, token))) = val;

        // Desereialize the sig so that it can be assembeld into a QC
        let origianl_sig: <BLSOverBN254CurveSignatureScheme as SignatureScheme>::Signature 
        = bincode_opts().deserialize(&sig.clone().0).expect("Deserialization on the signature shouldn't be able to fail.");

        

        let (total_stake_casted, total_vote_map) = self
            .total_vote_outcomes
            .entry(commitment)
            .or_insert_with(|| (0, BTreeMap::new()));

        let (da_stake_casted, da_vote_map) = self
            .da_vote_outcomes
            .entry(commitment)
            .or_insert_with(|| (0, BTreeMap::new()));

        let (yes_stake_casted, yes_vote_map) = self
            .yes_vote_outcomes
            .entry(commitment)
            .or_insert_with(|| (0, BTreeMap::new()));

        let (no_stake_casted, no_vote_map) = self
            .no_vote_outcomes
            .entry(commitment)
            .or_insert_with(|| (0, BTreeMap::new()));

        let (viewsync_precommit_stake_casted, viewsync_precommit_vote_map) = self
            .viewsync_precommit_vote_outcomes
            .entry(commitment)
            .or_insert_with(|| (0, BTreeMap::new()));

        let (viewsync_commit_stake_casted, viewsync_commit_vote_map) = self
            .viewsync_commit_vote_outcomes
            .entry(commitment)
            .or_insert_with(|| (0, BTreeMap::new()));

        let (viewsync_finalize_stake_casted, viewsync_finalize_vote_map) = self
            .viewsync_finalize_vote_outcomes
            .entry(commitment)
            .or_insert_with(|| (0, BTreeMap::new()));


        // Accumulate the stake for each leaf commitment rather than the total
        // stake of all votes, in case they correspond to inconsistent
        // commitments.

        // Check for duplicate vote
        if total_vote_map.contains_key(&key) {
            // error!("Duplicate vote");
            return Either::Left(self);
        }

        // update the active_keys and sig_lists
        self.signers.set(node_id, true);
        self.sig_lists.push(origianl_sig.clone());

        *total_stake_casted += u64::from(token.vote_count());
        total_vote_map.insert(key.clone(), (sig.clone(), vote_data.clone(), token.clone()));

        match vote_data {
            VoteData::DA(_) => {
                *da_stake_casted += u64::from(token.vote_count());
                da_vote_map.insert(key, (sig.clone(), vote_data.clone(), token));
            }
            VoteData::Yes(_) => {
                *yes_stake_casted += u64::from(token.vote_count());
                yes_vote_map.insert(key, (sig.clone(), vote_data.clone(), token));
            }
            VoteData::No(_) => {
                *no_stake_casted += u64::from(token.vote_count());
                no_vote_map.insert(key, (sig.clone(), vote_data.clone(), token));
            }
            VoteData::ViewSyncPreCommit(_) => {
                *viewsync_precommit_stake_casted += u64::from(token.vote_count());
                viewsync_precommit_vote_map.insert(key, (sig.clone(), vote_data.clone(), token));
            }
            VoteData::ViewSyncCommit(_) => {
                *viewsync_commit_stake_casted += u64::from(token.vote_count());
                viewsync_commit_vote_map.insert(key, (sig.clone(), vote_data.clone(), token));
            }
            VoteData::ViewSyncFinalize(_) => {
                *viewsync_finalize_stake_casted += u64::from(token.vote_count());
                viewsync_finalize_vote_map.insert(key, (sig.clone(), vote_data.clone(), token));
            }
            VoteData::Timeout(_) => {
                unimplemented!()
            }
        }

        // This is a messy way of accounting for the different vote types, but we will be replacing this code very soon
        if *total_stake_casted >= u64::from(self.success_threshold) {

            // Do assemble for QC here
            let real_qc_pp = <TYPES::SignatureKey as SignatureKey>::get_public_parameter(
                entries.clone(),
                U256::from(self.success_threshold.get()),
            );

            let real_qc_sig = <TYPES::SignatureKey as SignatureKey>::assemble(
                &real_qc_pp,
                self.signers.as_bitslice(),
                &self.sig_lists[..],
            );

            if *yes_stake_casted >= u64::from(self.success_threshold) {
                self.yes_vote_outcomes.remove(&commitment).unwrap().1;
                return Either::Right(AssembledSignature::Yes(real_qc_sig));
            } else if *no_stake_casted >= u64::from(self.failure_threshold) {
                self.total_vote_outcomes.remove(&commitment).unwrap().1;
                return Either::Right(AssembledSignature::No(real_qc_sig));
            } else if *da_stake_casted >= u64::from(self.success_threshold) {
                self.da_vote_outcomes.remove(&commitment).unwrap().1;
                return Either::Right(AssembledSignature::DA(real_qc_sig));
            } else if *viewsync_commit_stake_casted >= u64::from(self.success_threshold) {
                self.viewsync_commit_vote_outcomes.remove(&commitment).unwrap().1;
                return Either::Right(AssembledSignature::ViewSyncCommit(real_qc_sig));
            } else if *viewsync_finalize_stake_casted >= u64::from(self.success_threshold) {
                self.viewsync_finalize_vote_outcomes.remove(&commitment).unwrap().1;
                return Either::Right(AssembledSignature::ViewSyncFinalize(real_qc_sig));
            }
        }
        if *viewsync_precommit_stake_casted >= u64::from(self.failure_threshold) {

            let real_qc_pp = <TYPES::SignatureKey as SignatureKey>::get_public_parameter(
                entries.clone(),
                U256::from(self.success_threshold.get()),
            );

            let real_qc_sig = <TYPES::SignatureKey as SignatureKey>::assemble(
                &real_qc_pp,
                self.signers.as_bitslice(),
                &self.sig_lists[..],
            );

            self.viewsync_precommit_vote_outcomes.remove(&commitment).unwrap().1;
            return Either::Right(AssembledSignature::ViewSyncPreCommit(real_qc_sig));
        }
        Either::Left(self)
    }
}
