[package]
name = "utils"
version = { workspace = true }
edition = { workspace = true }
description = "Utils"

[dependencies]
tracing = { workspace = true }
derive_more = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
