[package]
name = "utils"
version = { workspace = true }
edition = { workspace = true }
description = "Utils"

[dependencies]
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
