[package]
authors = { workspace = true }
description = "Accompanying utilities used by hotshot."
edition = { workspace = true }
name = "hotshot-utils"
readme = "../README.md"
version = { workspace = true }

[dependencies]
bincode = { workspace = true }
hotshot-types = { workspace = true }

[lints]
workspace = true
