[package]
authors = ["Espresso Systems <hello@espressosys.com>"]
description = "Accompanying utilities used by hotshot."
edition = "2021"
name = "hotshot-utils"
readme = "../README.md"
version = "0.1.0"

[dependencies]
bincode = { workspace = true }
hotshot-constants = { path = "../constants" }

[lints]
workspace = true
