[package]
name = "hotshot-centralized-server-shared"
version = "0.1.1"
edition = "2021"

[dependencies]
bincode = "1.3.3"
hotshot-types = { version = "0.1.0", path = "../../types" }
serde = { version = "1.0.143", features = ["derive"] }
