[advisories]
ignore = [
    # Tungstenite allows remote attackers to cause a denial of service
    # Dependency of async-tungstenite -> tide-websockets / surf-disco
    "RUSTSEC-2023-0065",
    # DoS in WebPKI that comes with tide_disco
    "RUSTSEC-2023-0052"
]
