[advisories]
ignore = [
    # Tungstenite allows remote attackers to cause a denial of service
    # Dependency of async-tungstenite -> tide-websockets / surf-disco
    "RUSTSEC-2023-0065",
    # DoS in WebPKI that comes with tide_disco
    "RUSTSEC-2023-0052",
    # DoS in WebPKI that comes with tide_disco
    "RUSTSEC-2023-0052",
    # rustls vulnerability that could cause an infinite loop based on network input, coming from tide_disco
    "RUSTSEC-2024-0336",
    # Unfixed "Marvin" vulnerability in `RSA`, unused in sqlite dependency
    "RUSTSEC-2023-0071",
    # sqlx is only used for CDN tests. No newer version available yet
    "RUSTSEC-2024-0363",
]
