[advisories]
ignore = [
    # chrono 0.4.19, potential segfault
    # No safe upgrade is available
    # https://rustsec.org/advisories/RUSTSEC-2020-0159
    "RUSTSEC-2020-0159",

    # time 0.1.44 potential segfault
    # Dependency removed in https://github.com/EspressoSystems/atomicstore/pull/29
    # https://rustsec.org/advisories/RUSTSEC-2020-0071
    "RUSTSEC-2020-0071",

    # aes-soft 0.6.4 unmaintained
    # Dependency of tide -> http-types -> cookie -> aes-gcm -> aes
    # Fixed in cookie 0.16.0, waiting on http-types 3.0
    # https://rustsec.org/advisories/RUSTSEC-2021-0060
    "RUSTSEC-2021-0060",

    # aesni 0.10.0 unmaintained
    # Dependency of tide -> http-types -> cookie -> aes-gcm -> aesni
    # Fixed in cookie 0.16.0, waiting on http-types 3.0
    # https://rustsec.org/advisories/RUSTSEC-2021-0059
    "RUSTSEC-2021-0059",

    # cpuid-bool 0.2.0 unmaintained
    # renamed to `cpufeatures`
    # Dependency of tide -> http-types -> cookie -> aes-gcm -> ghash -> polyval
    # Fixed in cookie 0.16.0, waiting on http-types 3.0
    # https://rustsec.org/advisories/RUSTSEC-2021-0064
    "RUSTSEC-2021-0064",

    # Failure 0.1.8 official deprecated
    # Dependency of threshold_crypto
    # https://rustsec.org/advisories/RUSTSEC-2020-0036
    "RUSTSEC-2020-0036",

    # stdweb 0.4.20 unmaintained
    # Dependency of tide -> http-types -> cookie
    # Fixed in cookie 0.16.0, waiting on http-types 3.0
    # https://rustsec.org/advisories/RUSTSEC-2020-0056
    "RUSTSEC-2020-0056"
]
