# TOML file for node configuration.

title = "Node Configuration"

# Seed number used to generate secret key set for all nodes
seed = 1234

# Node information
[nodes]

[nodes.0]
ip = "localhost"
port = 19392

[nodes.1]
ip = "localhost"
port = 26940

[nodes.2]
ip = "localhost"
port = 21396

[nodes.3]
ip = "localhost"
port = 14967

[nodes.4]
ip = "localhost"
port = 18333

[nodes.5]
ip = "localhost"
port = 35254

[nodes.6]
ip = "localhost"
port = 47196
