[package]
name = "hotshot-constants"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
versioned-binary-serialization = { workspace = true }

[lints]
workspace = true
