[package]
name = "hotshot-macros"
version = "0.1.0"
edition = "2021"
description = "Macros for hotshot tests"

[dependencies]
# proc macro stuff
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = "1"

[lib]
proc-macro = true
[lints]
workspace = true
