rounds = 10
transactions_per_round = 1
node_index = 0
seed = [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
padding = 100
start_delay_seconds = 30

[config]
total_nodes = 10
committee_nodes = 5
max_transactions = 100
min_transactions = 0
next_view_timeout = 30000
timeout_ratio = [
    11,
    10,
]
round_start_delay = 1
start_delay = 1
num_bootstrap = 4

[config.propose_min_round_time]
secs = 0
nanos = 0

[config.propose_max_round_time]
secs = 1
nanos = 0

[web_server_config]
host = "127.0.0.1"
port = 9000

[da_web_server_config]
host = "127.0.0.1"
port = 9001

[web_server_config.wait_between_polls]
secs = 0
nanos = 100000000 # 100 ms

[da_web_server_config.wait_between_polls]
secs = 0
nanos = 100000000 # 100 ms
