rounds = 10
indexed_da = false
transactions_per_round = 10
manual_start_password = "tuktu6-tohnaX-gihxib"
node_index = 0
seed = [
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
]
transaction_size = 100
start_delay_seconds = 10
builder = "Simple"

[libp2p_config]
bootstrap_mesh_n_high = 4
bootstrap_mesh_n_low = 4
bootstrap_mesh_outbound_min = 2
bootstrap_mesh_n = 4
mesh_n_high = 4
mesh_n_low = 4
mesh_outbound_min = 2
mesh_n = 4
online_time = 10
num_txn_per_round = 0
server_mode = false

[config]
start_threshold = [ 8, 10 ]
num_nodes_with_stake = 10
num_nodes_without_stake = 0
staked_da_nodes = 10
non_staked_da_nodes = 0
fixed_leader_for_gpuvid = 1
next_view_timeout = 15_000
timeout_ratio = [ 11, 10 ]
round_start_delay = 1
start_delay = 10_000
num_bootstrap = 5
builder_urls = [ "https://builder.staging.testnet.espresso.network/" ]

[config.view_sync_timeout]
secs = 15
nanos = 0

[config.builder_timeout]
secs = 8
nanos = 0

[config.data_request_delay]
secs = 5
nanos = 0

[config.upgrade]
start_proposing_view = 1
stop_proposing_view = 0
start_voting_view = 1
stop_voting_view = 0
start_proposing_time = 1
stop_proposing_time = 0
start_voting_time = 1
stop_voting_time = 0

[combined_network_config.delay_duration]
secs = 5
nanos = 0
