/// `BlockContents` trait
pub mod block_contents;
/// Sortition trait
pub mod election;
/// `NodeImplementation` trait
pub mod node_implementation;
/// `State` trait
pub mod state;
/// `Storage` trait
pub mod storage;
