name: Build Workflow for ARM

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - '*/*'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, arm64]
    container:
      image: ghcr.io/espressosystems/nix:main
      volumes:
        - github_nix:/nix
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: cachix/cachix-action@v12
        with:
          name: espresso-systems-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Checkout Repository
        uses: actions/checkout@v3

      # sanity check that repository builds with nix
      - name: Build
        run: |
          nix develop -c cargo build --all-targets --profile=release-lto --workspace --features=full-ci
