name: Failing tests

on:
  push:
    branches:
      - '*/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Configure Git
        run: |
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf git://github.com/
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf ssh://git@github.com/

      - run: |
          set -ex
          export RUST_LOG=warn
          export RUST_LOG_FORMAT=compact
          cd phaselock-testing
          ../scripts/runfail.sh cargo test --release --all-features \
            -- ten_tx_five_nodes --test-threads=1
        name: Run until failure
        env:
          RUST_BACKTRACE: 1
