name: HotShot spec
on:
  push:
    branches:
      - '*/*'
      - 'main'
  pull_request:
    branches:
      - '*/*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - uses: cachix/cachix-action@v10
        with:
          name: espresso-systems-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Configure Git
        run: |
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf git://github.com/
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com/".insteadOf ssh://git@github.com/

      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Build artifacts
        run: |
          nix build .#hotshot-analysis -o hotshot-analysis.pdf
          nix build .#hotshot-paper -o hotshot-paper.pdf

      - uses: c-hive/gha-remove-artifacts@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Garbage collect old artifacts
        with:
          skip-tags: true
          skip-recent: 5
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_PAT }}
          age: '0 day'

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Upload pdf artifact
        with:
          name: hotshot-analysis.pdf
          path: ./hotshot-analysis.pdf

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Upload pdf artifact
        with:
          name: hotshot-paper.pdf
          path: ./hotshot-paper.pdf
