name: Lint (self-hosted)

on:
  push:
    branches:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' && github.run_number) || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        just_variants:
          - async-std
          #- tokio
    runs-on: [self-hosted]
    container: ghcr.io/espressosystems/devops-rust:stable
    steps:
      - uses: dtolnay/rust-toolchain@stable
        name: Install Current Rust
        with:
          components: "clippy, rustfmt"

      - name: Install Cap'n'Proto
        run: |
          apt-get update
          apt-get install -y capnproto

      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          prefix-key: ${{ matrix.just_variants }}

      - name: Run linting
        run: |
          just ${{ matrix.just_variants }} lint
