name: Lint (self-hosted)

on:
  push:
    branches:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    strategy:
      matrix:
        just_variants:
          - async_std
          #- tokio
    runs-on: [self-hosted]
    steps:
      - uses: dtolnay/rust-toolchain@stable
        name: Install Current Rust
        with:
          components: "clippy, rustfmt"

      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          prefix-key: ${{ matrix.just_variants }}

      - name: Run linting
        run: |
          just ${{ matrix.just_variants }} lint
