name: Crypto Tests

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        just_variants:
          - async_std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          shared-key: ""
          prefix-key: ${{ matrix.just_variants }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Install Just
        run: |
          wget https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-unknown-linux-musl.tar.gz
          tar -vxf just-1.14.0-x86_64-unknown-linux-musl.tar.gz just
          sudo cp just /usr/bin/just
      - name: Unit and integration tests for all crates in workspace
        run: |
          just ${{ matrix.just_variants }} test_crypto
        timeout-minutes: 60
        env:
          RUST_BACKTRACE: full

