name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v15
        with:
          pr-title: "Weekly PR to bump flake.nix" # Title of PR to be created
          token: ${{ secrets.ORG_GITHUB_PAT }} # PAT necessary to run CI on opened PR
